### ISSUE TITLE
Documentation: Code tab ideas for simple tasks

### ISSUE THREAD

**Issue by mattjshannon** [PAHdb/cookbook#2]
Basic things:

- Displaying a spectrum
- Displaying a structure
- Displaying information
- Searching
- Creating an absorption spectrum
- Creating an emission spectrum
- Using an emission model
- Fitting a spectrum (eventually)

**Comment by mattjshannon** [comment]
Should be able to use Pygments for RST (http://pygments.org/languages/) to highlight IDL.

**Comment by PAHdb** [comment]
Using sphinx-tabs.
